DATA:
  test:
    adaptive: false
    angle: &id001
    - 180
    - 180
    - 180
    batch_size: 8
    bsphere: sphere
    center: &id002
    - -1.0
    - -1.0
    - -1.0
    depth: 6
    disable: false
    distort: false
    filelist: /penwan/dataset/ShapeNet/filelist/all_val.txt
    full_depth: 3
    in_memory: false
    interval: &id003
    - 1
    - 1
    - 1
    jitter: 0.0
    load_occu: false
    load_sdf: true
    location: /penwan/dataset/ShapeNet/dataset
    name: shapenet
    node_dis: true
    node_feat: false
    normal_axis: ''
    num_workers: 8
    offset: 0.0
    point_scale: 0.5
    radius: -1.0
    sample_surf_points: false
    scale: 0.0
    shuffle: false
    split_label: true
    uniform: false
  train:
    adaptive: false
    angle: *id001
    batch_size: 16
    bsphere: sphere
    center: *id002
    depth: 6
    disable: false
    distort: false
    filelist: /penwan/dataset/ShapeNet/filelist/all_train.txt
    full_depth: 3
    in_memory: false
    interval: *id003
    jitter: 0.0
    load_occu: false
    load_sdf: true
    location: /penwan/dataset/ShapeNet/dataset
    name: shapenet
    node_dis: true
    node_feat: false
    normal_axis: ''
    num_workers: 8
    offset: 0.0
    point_scale: 0.5
    radius: -1.0
    sample_surf_points: false
    scale: 0.0
    shuffle: true
    split_label: true
    uniform: false
LOSS:
  label_smoothing: 0.0
  loss_type: sdf_reg_loss
  name: shapenet
  num_class: 40
  weights:
  - 1.0
  - 1.0
MODEL:
  bottleneck: 4
  channel: 5
  depth: 6
  depth_out: 6
  dropout:
  - 0.0
  factor: 1
  find_unused_parameters: false
  full_depth: 3
  interp: linear
  name: graph_ounet
  nempty: false
  nout: 4
  resblock_num: 3
  resblock_type: basic
  sync_bn: false
  upsample: nearest
  use_checkpoint: false
SOLVER:
  alias: ep300_poly_resblk2_weight1
  ckpt: ''
  ckpt_num: 40
  dist_url: tcp://localhost:10001
  eval_epoch: 1
  eval_step: -1
  gamma: 0.1
  gpu:
  - 0
  - 1
  - 2
  - 3
  log_per_iter: 50
  logdir: /penwan/logs/shapenet/1220_ep300_poly_resblk2_weight1
  lr: 0.001
  lr_power: 0.9
  lr_type: poly
  max_epoch: 300
  progress_bar: false
  resolution: 128
  run: train
  save_sdf: false
  sdf_scale: 0.9
  step_size:
  - 160
  - 240
  test_every_epoch: 20
  type: adamw
  weight_decay: 0.01
SYS:
  cmds: completion.py --config configs/shapenet.yaml SOLVER.gpu 0,1,2,3 SOLVER.logdir
    /penwan/logs/shapenet/1220 SOLVER.alias ep300_poly_resblk2_weight1 SOLVER.max_epoch
    300 SOLVER.progress_bar False DATA.train.location /penwan/dataset/ShapeNet/dataset
    DATA.train.filelist /penwan/dataset/ShapeNet/filelist/all_train.txt DATA.test.location
    /penwan/dataset/ShapeNet/dataset DATA.test.filelist /penwan/dataset/ShapeNet/filelist/all_val.txt
