# --------------------------------------------------------
# Dual Octree Graph Networks
# Copyright (c) 2022 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: evaluate
  # ckpt: logs/completion_shapenet/checkpoints/00300.model.pth
  ckpt: logs/ocnn_ounet/ounet/checkpoints/00240.model.pth
  alias: eval

  logdir: logs/ocnn_ounet/ounet/3.12
  # logdir: logs/completion_shapenet_eval
  max_epoch: 300
  test_every_epoch: 20
  log_per_iter: 50
  ckpt_num: 20

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  step_size: (160,240)  # milestones

DATA:
  test:
    name: bas-relief

    # octree building
    depth: 6
    full_depth: 2

    # data augmentation, add noise only
    distort: False

    # data loading
    location: /home/sujianping/Bas-relief/Dualocnn/Dataset/bas-relief-dataset/DualOcnnData/dataset
    model_filelist: /home/sujianping/Bas-relief/Dualocnn/Dataset/bas-relief-dataset/DualOcnnData/dataset/model_val.txt
    relief_filelist: /home/sujianping/Bas-relief/Dualocnn/Dataset/bas-relief-dataset/DualOcnnData/dataset/relief_val.txt
    batch_size: 16
    shuffle: False
    num_workers: 4


MODEL:
  name: ocnn_ounet
  feature: L
  channel: 3
  depth: 6
  nout: 4
  full_depth: 2

LOSS:
  name: ocnn_ae
