SOLVER:
  gpu: 0,
  logdir: logs/ae/0609_resnet_decode_shape
  ckpt: logs/ae/0609_resnet/model/iter_320000.ckpt
  run: decode_shape
  test_iter: 200

DATA:
  test: 
    dtype: points
    depth: 6
    location: dataset/ocnn_completion/completion_test_points.tfrecords
    batch_size: 1
    distort: False
    offset: 0.0
    node_dis: True
    split_label: True
    shuffle: 0

MODEL:
  name: resnet
  channel: 4
  nout: 32   # The channel of the hidden code
  depth: 6

LOSS:
  weight_decay: 0.0005