# To test the model with the tensorflow checkpoint

SOLVER:
  gpu: 0,
  logdir: logs/m40/0322_ocnn_octree_test
  ckpt: logs/m40/0322_ocnn_octree/model/iter_160000.ckpt
  run: test
  test_iter: 925

DATA:
  test: 
    dtype: octree
    depth: 5
    location: dataset/ModelNet40/m40_5_2_12_test_octree.tfrecords
    shuffle: 0
    batch_size: 32
    x_alias: data

MODEL:
  name: ocnn
  channel: 3
  nout: 40
  depth: 5

LOSS:
  num_class: 40
  weight_decay: 0.0005
